root = getenv('GITHUB_WORKSPACE');
source_file = fullfile(root, 'external', 'muscat', 'Mission', 'Mission_NISAR_2SC.m');
main_file = fullfile(root, 'external', 'muscat', 'Main', 'main_v3.m');
artifact_dir = fullfile(root, 'artifacts');
if ~isfolder(artifact_dir), mkdir(artifact_dir); end

source = fileread(source_file);
main = fileread(main_file);
assert(count(source, 'init_data.num_hardware_exists.num_reaction_wheel = 0;') == 1);
source = replace(source, 'init_data.num_hardware_exists.num_reaction_wheel = 0;', ...
    'init_data.num_hardware_exists.num_reaction_wheel = 4;');
source = replace(source, '% init_data.time_step_attitude = 5;', 'init_data.time_step_attitude = 1;');
source = replace(source, 'init_data.flag_realtime_plotting = 1;', 'init_data.flag_realtime_plotting = 0;');
source = replace(source, 'init_data.flag_save_plots = 1;', 'init_data.flag_save_plots = 0;');
source = replace(source, 'init_data.t_final = 8*86400;', 'init_data.t_final = 180;');
source = replace(source, 'init_data.t_final = 4*86400;', 'init_data.t_final = 180;');
source = replace(source, 'init_data.t_final = 1*86400;', 'init_data.t_final = 180;');

old_call = 'func_main_software_SC_control_attitude(mission.true_SC{i_SC}.software_SC_control_attitude, mission, i_SC);';
assert(count(main, old_call) == 1);
main = replace(main, old_call, 'func_muscat_heterogeneous_attitude_control(mission, i_SC);');
custom_main = fullfile(root, 'external', 'muscat', 'Main', 'main_muscat_heterogeneous.m');
writelines(string(main), custom_main);

start_marker = '%% Save All Data';
main_marker = 'run main_v3.m';
first_save = strfind(source, start_marker);
assert(numel(first_save) == 2 && count(source, main_marker) == 1);
prefix = source(1:first_save(1)-1);

policies = {'permanent','two_layer'};
for p = 1:numel(policies)
    policy = policies{p};
    setup = sprintf([ ...
        '\n%% Frozen MuSCAT source-class designed-heterogeneity intervention\n', ...
        'global MUSCAT_HETERO\n', ...
        'MUSCAT_HETERO = struct(); MUSCAT_HETERO.k=0; MUSCAT_HETERO.policy=''%s'';\n', ...
        'MUSCAT_HETERO.rho=1.5; MUSCAT_HETERO.observer_gain=0.08; MUSCAT_HETERO.coupling_gain=0.06;\n', ...
        'MUSCAT_HETERO.target_rate=2e-4; MUSCAT_HETERO.target_frequency=0.025;\n', ...
        'MUSCAT_HETERO.gate_threshold=2.5e-4; MUSCAT_HETERO.pin=[1;0];\n', ...
        'MUSCAT_HETERO.A_info=[0 0;1 0]; MUSCAT_HETERO.A_physical=[0 1;1 0];\n', ...
        'MUSCAT_HETERO.kd=[8500;10500]; MUSCAT_HETERO.bias_torque=[0 0 0;0 0 0.012];\n', ...
        'MUSCAT_HETERO.z=[0 0 0.00035;0 0 -0.00030];\n', ...
        'MUSCAT_HETERO.target=zeros(1000,3); MUSCAT_HETERO.omega=zeros(1000,2,3);\n', ...
        'MUSCAT_HETERO.z_store=zeros(1000,2,3); MUSCAT_HETERO.residual=zeros(1000,2);\n', ...
        'MUSCAT_HETERO.edge_count=zeros(1000,1); MUSCAT_HETERO.applied_proxy=zeros(1000,2,3);\n', ...
        'mission.true_SC{1}.true_SC_body.total_MI = 0.94*mission.true_SC{1}.true_SC_body.total_MI;\n', ...
        'mission.true_SC{2}.true_SC_body.total_MI = 1.07*mission.true_SC{2}.true_SC_body.total_MI;\n', ...
        'for hs=1:mission.num_SC, for hw=1:4, mission.true_SC{hs}.true_SC_reaction_wheel{hw}.maximum_torque=0.2*(0.9+0.2*(hs-1)); mission.true_SC{hs}.true_SC_reaction_wheel{hw}.maximum_acceleration=mission.true_SC{hs}.true_SC_reaction_wheel{hw}.maximum_torque/mission.true_SC{hs}.true_SC_reaction_wheel{hw}.moment_of_inertia; end, end\n', ...
        'run(''main_muscat_heterogeneous.m'');\n', ...
        'k=MUSCAT_HETERO.k; rows=zeros(k*2,14); q=0;\n', ...
        'for kk=1:k, for hs=1:2, q=q+1; rows(q,:)=[kk,hs,MUSCAT_HETERO.target(kk,:),reshape(MUSCAT_HETERO.omega(kk,hs,:),1,3),reshape(MUSCAT_HETERO.z_store(kk,hs,:),1,3),MUSCAT_HETERO.residual(kk,hs),MUSCAT_HETERO.edge_count(kk),norm(reshape(MUSCAT_HETERO.applied_proxy(kk,hs,:),1,3))]; end, end\n', ...
        'assert(all(isfinite(rows),''all'') && any(rows(:,14)>0));\n', ...
        'writematrix(rows,fullfile(getenv(''GITHUB_WORKSPACE''),''artifacts'',''muscat_heterogeneous_%s.csv'')); return\n'], policy, policy);
    out = fullfile(root, 'external', 'muscat', 'Mission', ['Mission_NISAR_2SC_HETERO_', policy, '.m']);
    fid=fopen(out,'w'); assert(fid>0); fwrite(fid,[prefix,setup]); fclose(fid);
end
