root = getenv('GITHUB_WORKSPACE');
source_file = fullfile(root, 'external', 'muscat', 'Mission', 'Mission_NISAR_2SC.m');
output_file = fullfile(root, 'external', 'muscat', 'Mission', 'Mission_NISAR_2SC_MATLAB_SMOKE.m');
artifact_dir = fullfile(root, 'artifacts');
if ~isfolder(artifact_dir), mkdir(artifact_dir); end

text = fileread(source_file);
replacements = {
    'init_data.t_final = 8*86400;', 'init_data.t_final = 60;';
    'init_data.t_final = 4*86400;', 'init_data.t_final = 60;';
    'init_data.t_final = 1*86400;', 'init_data.t_final = 60;';
    'init_data.flag_realtime_plotting = 1;', 'init_data.flag_realtime_plotting = 0;';
    'init_data.flag_save_plots = 1;', 'init_data.flag_save_plots = 0;'};
for k = 1:size(replacements,1)
    assert(count(text, replacements{k,1}) == 1, 'Unexpected source occurrence count');
    text = replace(text, replacements{k,1}, replacements{k,2});
end

start_marker = '%% Save All Data';
main_marker = 'run main_v3.m';
assert(count(text, start_marker) == 2, 'Expected two save sections');
first_save = strfind(text, start_marker);
main_call = strfind(text, main_marker);
assert(numel(main_call) == 1 && first_save(1) < main_call, 'Unexpected mission structure');

prefix = text(1:first_save(1)-1);
suffix_start = main_call + strlength(main_marker);
suffix = text(suffix_start:end);
run_and_export = sprintf([ ...
    '\n%% Frozen CI smoke: no pre-run visualization or serialization\n', ...
    'run main_v3.m\n', ...
    'summary = zeros(mission.num_SC, 27);\n', ...
    'for replay_i = 1:mission.num_SC\n', ...
    ' nav = mission.true_SC{replay_i}.true_SC_navigation;\n', ...
    ' adc = mission.true_SC{replay_i}.true_SC_adc;\n', ...
    ' ctl = mission.true_SC{replay_i}.software_SC_control_attitude;\n', ...
    ' summary(replay_i,:) = [replay_i, nav.position_relative_target(:)'', ', ...
    'nav.velocity_relative_target(:)'', adc.attitude(:)'', adc.angular_velocity(:)'', ', ...
    'ctl.desired_control_torque(:)'', adc.control_torque(:)'', ', ...
    'double(nav.flag_SC_crashed), nav.control_force(:)'', nav.disturbance_force(:)''];\n', ...
    'end\n', ...
    'assert(all(isfinite(summary), ''all''));\n', ...
    'writematrix(summary, fullfile(getenv(''GITHUB_WORKSPACE''), ''artifacts'', ''muscat_matlab_smoke.csv''));\n', ...
    'physical = zeros(mission.num_SC, 11);\n', ...
    'for replay_i = 1:mission.num_SC\n', ...
    ' body = mission.true_SC{replay_i}.true_SC_body;\n', ...
    ' physical(replay_i,:) = [replay_i, body.total_mass, reshape(body.total_MI, 1, 9)];\n', ...
    'end\n', ...
    'assert(all(isfinite(physical), ''all'') && all(physical(:,2) > 0));\n', ...
    'writematrix(physical, fullfile(getenv(''GITHUB_WORKSPACE''), ''artifacts'', ''muscat_physical_parameters.csv''));\n', ...
    'fid = fopen(fullfile(getenv(''GITHUB_WORKSPACE''), ''artifacts'', ''source_commit.txt''), ''w'');\n', ...
    'fprintf(fid, ''d8a0739426a23b3e25dc66e0fa4b7152972c11df\\n''); fclose(fid);\n', ...
    'return\n']);

assert(~isempty(suffix));
fid = fopen(output_file, 'w');
assert(fid > 0, 'Cannot create generated mission');
fwrite(fid, [prefix, run_and_export]);
fclose(fid);
