% Generate the frozen MuSCAT V3 held-out matrix without refitting V2.
root = getenv('GITHUB_WORKSPACE');
source_file = fullfile(root, 'external', 'muscat', 'Mission', 'Mission_NISAR_2SC.m');
main_file = fullfile(root, 'external', 'muscat', 'Main', 'main_v3.m');
artifact_dir = fullfile(root, 'artifacts');
if ~isfolder(artifact_dir), mkdir(artifact_dir); end

source = fileread(source_file); main = fileread(main_file);
assert(count(source, 'init_data.num_hardware_exists.num_reaction_wheel = 0;') == 1);
source = replace(source, 'init_data.num_hardware_exists.num_reaction_wheel = 0;', ...
    'init_data.num_hardware_exists.num_reaction_wheel = 4;');
source = replace(source, '% init_data.time_step_attitude = 5;', 'init_data.time_step_attitude = 1;');
source = replace(source, 'init_data.flag_realtime_plotting = 1;', 'init_data.flag_realtime_plotting = 0;');
source = replace(source, 'init_data.flag_save_plots = 1;', 'init_data.flag_save_plots = 0;');
source = replace(source, 'init_data.t_final = 8*86400;', 'init_data.t_final = 180;');
source = replace(source, 'init_data.t_final = 4*86400;', 'init_data.t_final = 180;');
source = replace(source, 'init_data.t_final = 1*86400;', 'init_data.t_final = 180;');
old_call = 'func_main_software_SC_control_attitude(mission.true_SC{i_SC}.software_SC_control_attitude, mission, i_SC);';
assert(count(main, old_call) == 1);
main = replace(main, old_call, 'func_muscat_heterogeneous_attitude_control(mission, i_SC);');
writelines(string(main), fullfile(root, 'external', 'muscat', 'Main', 'main_muscat_heterogeneous.m'));
first_save = strfind(source, '%% Save All Data');
assert(numel(first_save) == 2 && count(source, 'run main_v3.m') == 1);
prefix = source(1:first_save(1)-1);

rho_grid = [0.10 0.20 0.40 0.80 1.60 2.40];
% Rows are held out from V2. Columns: I1,I2,T1,T2,bias,z1,z2,target-visible.
conditions = [ ...
  0.90 1.10 0.180 0.220 0.018  0.00046 -0.00022 1; ...
  0.91 1.05 0.182 0.218 0.007  0.00027 -0.00044 2; ...
  0.96 1.09 0.195 0.210 0.015  0.00039 -0.00027 1; ...
  0.97 1.03 0.200 0.205 0.006  0.00031 -0.00034 2; ...
  0.92 1.02 0.188 0.220 0.011  0.00048 -0.00020 1; ...
  0.98 1.10 0.198 0.212 0.017  0.00026 -0.00045 2; ...
  0.94 1.09 0.181 0.219 0.013  0.00041 -0.00025 1; ...
  0.99 1.04 0.197 0.208 0.008  0.00030 -0.00040 2];
policies = {'permanent','two_layer'};
driver = fullfile(root, 'external', 'muscat', 'Mission', 'run_muscat_participation_v3_heldout.m');
fid_driver = fopen(driver, 'w'); assert(fid_driver > 0);
fprintf(fid_driver, '%% Generated frozen held-out driver\n');

for c = 1:size(conditions,1)
  visible = round(conditions(c,8));
  if visible == 1, pin='[1;0]'; info='[0 0;1 0]'; else, pin='[0;1]'; info='[0 1;0 0]'; end
  for r = 1:numel(rho_grid)
    for p = 1:numel(policies)
      policy=policies{p}; rho=rho_grid(r); tag=sprintf('c%02d_r%02d_%s',c,r,policy);
      setup=sprintf([ ...
        '\n%% Frozen MuSCAT participation V3 held-out condition\n', ...
        'global MUSCAT_HETERO\nMUSCAT_HETERO=struct(); MUSCAT_HETERO.k=0; MUSCAT_HETERO.policy=''%s'';\n', ...
        'MUSCAT_HETERO.rho=%.17g; MUSCAT_HETERO.observer_gain=0.08; MUSCAT_HETERO.coupling_gain=0.06;\n', ...
        'MUSCAT_HETERO.target_rate=2e-4; MUSCAT_HETERO.target_frequency=0.025; MUSCAT_HETERO.gate_threshold=2.5e-4;\n', ...
        'MUSCAT_HETERO.pin=%s; MUSCAT_HETERO.A_info=%s; MUSCAT_HETERO.A_physical=[0 1;1 0];\n', ...
        'MUSCAT_HETERO.kd=[8500;10500]; MUSCAT_HETERO.bias_torque=[0 0 0;0 0 %.17g];\n', ...
        'MUSCAT_HETERO.z=[0 0 %.17g;0 0 %.17g]; MUSCAT_HETERO.target=zeros(1000,3);\n', ...
        'MUSCAT_HETERO.omega=zeros(1000,2,3); MUSCAT_HETERO.z_store=zeros(1000,2,3); MUSCAT_HETERO.residual=zeros(1000,2);\n', ...
        'MUSCAT_HETERO.edge_count=zeros(1000,1); MUSCAT_HETERO.applied_proxy=zeros(1000,2,3);\n', ...
        'mission.true_SC{1}.true_SC_body.total_MI=%.17g*mission.true_SC{1}.true_SC_body.total_MI;\n', ...
        'mission.true_SC{2}.true_SC_body.total_MI=%.17g*mission.true_SC{2}.true_SC_body.total_MI;\n', ...
        'lims=[%.17g %.17g]; for hs=1:2, for hw=1:4, mission.true_SC{hs}.true_SC_reaction_wheel{hw}.maximum_torque=lims(hs); mission.true_SC{hs}.true_SC_reaction_wheel{hw}.maximum_acceleration=lims(hs)/mission.true_SC{hs}.true_SC_reaction_wheel{hw}.moment_of_inertia; end, end\n', ...
        'run(''main_muscat_heterogeneous.m''); k=MUSCAT_HETERO.k; rows=zeros(k*2,17); q=0;\n', ...
        'for kk=1:k, for hs=1:2, q=q+1; rows(q,:)=[%d,%.17g,%d,kk,hs,MUSCAT_HETERO.target(kk,:),reshape(MUSCAT_HETERO.omega(kk,hs,:),1,3),reshape(MUSCAT_HETERO.z_store(kk,hs,:),1,3),MUSCAT_HETERO.residual(kk,hs),MUSCAT_HETERO.edge_count(kk),norm(reshape(MUSCAT_HETERO.applied_proxy(kk,hs,:),1,3))]; end, end\n', ...
        'assert(all(isfinite(rows),''all'') && any(rows(:,17)>0)); writematrix(rows,fullfile(getenv(''GITHUB_WORKSPACE''),''artifacts'',''muscat_heldout_%s.csv''));\n'], ...
        policy,rho,pin,info,conditions(c,5),conditions(c,6),conditions(c,7),conditions(c,1),conditions(c,2),conditions(c,3),conditions(c,4),c,rho,visible,tag);
      out=fullfile(root,'external','muscat','Mission',['Mission_MUSCAT_HELDOUT_',tag,'.m']);
      fid=fopen(out,'w'); assert(fid>0); fwrite(fid,[prefix,setup]); fclose(fid);
      fprintf(fid_driver,'run(''%s'');\n',out);
    end
  end
end
fclose(fid_driver);

