#!/usr/bin/env python3
"""Audit whether public EPFL fields identify per-agent plant heterogeneity."""
from __future__ import annotations
import argparse, json
from pathlib import Path
import numpy as np
from scipy.io import loadmat


def main():
    parser=argparse.ArgumentParser(); parser.add_argument('dataset_root',type=Path)
    parser.add_argument('--output',type=Path,required=True); args=parser.parse_args()
    counts={"pf_with_requested_acceleration":0,"mpc_with_requested_acceleration":0,
            "hitl_records":0,"hitl_with_applied_control":0,"usable_identification_records":0}
    pf_step_errors=[]; hitl_issues=[]
    for path in args.dataset_root.rglob('workspace.mat'):
        try: data=loadmat(path,squeeze_me=True,struct_as_record=False)
        except Exception: continue
        relative=str(path.relative_to(args.dataset_root))
        is_pf='/pf/' in '/'+relative; is_hitl='/hitl/' in '/'+relative
        if is_pf and 'accel_history' in data:
            counts['pf_with_requested_acceleration']+=1
            v=np.asarray(data['vel_history'],float); u=np.asarray(data['accel_history'],float)
            t=np.asarray(data['time_history'],float).reshape(-1)
            length=min(len(u),len(v)-1); dt=np.diff(t[:length+1])[:,None]
            pf_step_errors.append(float(np.sqrt(np.mean((v[:length]+dt*u[:length]-v[1:length+1])**2))))
        if '/mpc/' in '/'+relative and 'U_history' in data:
            counts['mpc_with_requested_acceleration']+=1
        if is_hitl:
            counts['hitl_records']+=1
            applied=any(k in data for k in ('applied_control','motor_command','thrust_history'))
            counts['hitl_with_applied_control']+=int(applied)
            t=np.asarray(data.get('time_history',[]))
            cmd=np.asarray(data.get('pos_cmd_history',[])); state=np.asarray(data.get('pos_history',[]))
            issues=[]
            if not applied: issues.append('no_applied_control_or_thrust')
            if t.size<2 or len(np.unique(t))<3: issues.append('nonidentifying_time_axis')
            if len(cmd)!=len(state): issues.append('command_state_length_mismatch')
            if 'vel_history' not in data: issues.append('no_velocity')
            hitl_issues.append({"record":relative,"issues":issues})
            counts['usable_identification_records']+=int(not issues)
    report={
      "audit":"public UAV heterogeneity identifiability",
      "counts":counts,
      "pf_double_integrator_velocity_rmse_max":max(pf_step_errors) if pf_step_errors else None,
      "hitl_issues":hitl_issues,
      "identified":counts['usable_identification_records']>0,
      "decision":"NOT_IDENTIFIABLE_FROM_CURRENT_PUBLIC_FIELDS",
      "reason":("PF/MPC acceleration channels are commands generated by the homogeneous simulation. "
                "The sole HITL record lacks applied control/thrust and an identifying time/alignment contract. "
                "Per-agent effectiveness, drag and actuator lag therefore cannot be uniquely estimated."),
      "minimum_external_data":("timestamped requested and applied control or motor thrust, position and velocity "
                               "for every vehicle, platform identity, excitation sufficient for each parameter, "
                               "and an independently frozen calibration/validation split")
    }
    args.output.parent.mkdir(parents=True,exist_ok=True)
    args.output.write_text(json.dumps(report,indent=2)+'\n'); print(json.dumps(report,indent=2))

if __name__=='__main__': main()
